name: Run main.py
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Decrypt credentials
        working-directory: ./secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output api_credentials.json api_credentials.json.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output moodle_credentials.json moodle_credentials.json.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output token.json token.json.gpg
      - name: Run main.py
        run: |
          python main.py