name: Run main.py
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'pip'
      - name: Run main.py
        run: |
          python3 main.py